### ISSUE TITLE
add support for "from_env" to config

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#139]
this would be used for something like:

```yaml
locations:
  here:
    rack: 
      from_env: HOSTNAME
    board: vec
```

so we can easily get differing rack-ids per vec (see:  https://github.com/vapor-ware/vec-testbed/issues/174 for more context)
