### ISSUE TITLE
should we have prototype configs, or should they be built-in?

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#144]
at the time, it made sense to me to have prototype configurations as well as the device instance configurations. 

the data the prototype configs provide are still needed, but I'm questioning whether they need to be given via configuration files (just one more thing to manage), or if they can be built in to the plugin by virtue of having a handler for a given device type.

that is to say, instead of having something like
```yaml
version: 1.0
prototypes:
  - type: temperature
    model: MAX11610
    manufacturer: Maxim Integrated
    protocol: i2c
    output:
      - type: temperature
        unit:
          name: degrees celsius
          symbol: C
        precision: 2
        range:
          min: 0
          max: 100
```

we could just make it part of the device handler in some way
```go
protoCfg := Max11610Proto{
	Type: "temperature",
	Model: "MAX11610",
	Manufacturer: "Maxim Integrated",
	Protocol: "i2c",
	Output: []OutputProto{
		{
			Type: "temperature",
			Unit: OutputUnit{
				Name: "degrees celcius",
				Symbol: "C",
			},
			Precision: 2,
			Range: OutputRange{
				Min: 0,
				Max: 100,
			},
		},
	},
}
```

A data structure like this already exists because its what we marshal the config into, so it still leaves the possibility of configuring via config, if desired. Having them just be part of the code seems fine in the cases we've had because the proto configs don't really change per device.
