### ISSUE TITLE
allow template strings in tags and context values

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#447]
The SDK  should provide support for go template strings in device tag and context configurations, e.g.

```yaml
instances:
- type: foo
   tags:
   - 'synse/sdk:{{ fromEnv SOMETHING }}'   
   context:
     key: '{{ fromEnv SOMETHING }}'
```

This is useful in cases where plugins may be deployed in a cluster as a DaemonSet where the plugin devices are specific to the node's hardware and we want tags/context to relate to that node.
