### ISSUE TITLE
support multiple device instance types in single config file

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#52]
for simplicity/organization, i've been keeping device configs in separate files based on device model, e.g. 
```
config/
  |- proto/
  +- device/
    |- max11610_thermistor.yml
    +- pca9642_led.yml
```
but when starting to put together k8s configs, that gets tedious, especially for a bunch of device types. each have to be their own configmap, each mounted in appropriately.

while we can/should still support this, we should also support "mono"-configs, e.g. where all device configurations are in a single file. the structure of the config file would have to change. perhaps something like:
```yaml
version: 2.0
locations:
  r1vec:
    rack: rack-1
    board: vec
devices:
  - type: temperature
    model: MAX11610
    instances:
      - channel: "0000"
        location: r1vec
        info: "rack temperature top middle"
      - channel: "0001"
        location: r1vec
        info: "rack temperature top right"
  - type: led
    model: PCA9632
    instances:
      - channel: "0014"
        location: r1vec
        info: "chamber LED"
```

which could also be easily used for a single-config-per-device-model strategy
```yaml
version: 2.0
locations:
  r1vec:
    rack: rack-1
    board: vec
devices:
  - type: temperature
    model: MAX11610
    instances:
      - channel: "0000"
        location: r1vec
        info: "rack temperature top middle"
      - channel: "0001"
        location: r1vec
        info: "rack temperature top right"
```

```yaml
version: 2.0
locations:
  r1vec:
    rack: rack-1
    board: vec
devices:
  - type: led
    model: PCA9632
    instances:
      - channel: "0014"
        location: r1vec
        info: "chamber LED"
```
